// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQJGtuNbGsEmfx2XHFNC3XkCvhP-lDtlU',
    appId: '1:601423066247:web:d11801554f8d9588d77422',
    messagingSenderId: '601423066247',
    projectId: 'myfirstproject-355df',
    authDomain: 'myfirstproject-355df.firebaseapp.com',
    databaseURL: 'https://myfirstproject-355df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfirstproject-355df.appspot.com',
    measurementId: 'G-P6C6RGRCR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqxTfntCFFFlEMfOZIpZIcCVk4nyUOkYE',
    appId: '1:601423066247:android:a5daebee5bb18269d77422',
    messagingSenderId: '601423066247',
    projectId: 'myfirstproject-355df',
    databaseURL: 'https://myfirstproject-355df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfirstproject-355df.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQJGtuNbGsEmfx2XHFNC3XkCvhP-lDtlU',
    appId: '1:601423066247:web:d11801554f8d9588d77422',
    messagingSenderId: '601423066247',
    projectId: 'myfirstproject-355df',
    authDomain: 'myfirstproject-355df.firebaseapp.com',
    databaseURL: 'https://myfirstproject-355df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfirstproject-355df.appspot.com',
    measurementId: 'G-P6C6RGRCR5',
  );
}
